### ISSUE TITLE
Exports object instead of functions

### ISSUE THREAD

**Issue by ArmorDarks** [systemjs/systemjs#1629]
Hello there!

I've encountered strange issue, which I can't figure out.

For instance, everything works with JSPM 0.17.0-beta.21, but doesn't with beta.41, so I assume it has something to do with changes in SystemJS 0.20.0 and above.

I'm using [redux-form](https://github.com/erikras/redux-form)

The error occurs when I invoke `reduxForm`, provided by lib wrapper for React components

See this simplest possible snippet:

```js
import React from 'react'
import { Field, reduxForm } from 'redux-form'

const ContactForm = () => {
  return (
    <form>
      <Field name='email' component='input' type='email'/>
    </form>
  )
}

export default reduxForm({ form: 'contact' })(ContactForm)
```

On running this, SystemJS will throw following error:

![chrome_2017-03-24_17-57-44](https://cloud.githubusercontent.com/assets/4460311/24303685/8bad8fec-10bf-11e7-965e-4722f374104e.png)

As you can see, it says that `actionCreator.bind` is not a function, though it worked in JSPM beta.21

I tried to log out content of `actionCreator` with JSPM beta.41, and it indeed wasn't a function, but an Object:

![chrome_2017-03-24_17-58-14](https://cloud.githubusercontent.com/assets/4460311/24303723/c2df11fc-10bf-11e7-9cbc-167b01c893e6.png)

I reverted to JSPM beta.21, and made same log of `actionCreator`:

![chrome_2017-03-24_18-11-04](https://cloud.githubusercontent.com/assets/4460311/24303742/d2a6c4fe-10bf-11e7-8010-2063fe8c688e.png)

So, as you can see, it works, because in older JSPM `actionCreator` indeed a function.

I guess it has something to do with exports. For some reason newer SystemJS treats it as ES module, while it is a CommonJS module.

I tried to override:

```js
    "overrides": {
      "npm:redux-form@6.6.0": {
        "format": "cjs",
        "esModule": false
      }
    }
```

but it did result in same error, and `actionCreator` still outputting Object with `esModule` set to `true`

Do I miss something? Or it's SystemJS bug?

**Comment by guybedford** [comment]
I think the problem here seems to come from this line - https://github.com/erikras/redux-form/blob/v6.6.0/src/reduxForm.js#L26.

Can you verify that `formActions` is being populated correctly from `importedActions` through the object rest assignment around there?

The issue seems definitely related to the way the `actionCreator` content you logged above is being treated, although I'm not sure it's exactly that function display issue.

**Comment by ArmorDarks** [comment]
I'm not very familiar with internals of redux-form, but I will try to dig it.

I have few concerns, though... Maybe it somehow related to transpilation after publishing to NPM?

For instance, during publishing library compiled to support cjs, es and umd formats, and due to this result files looks different than in sources.

For instance, you can see here `lib` dir, which is cjs format, `es` dir, which contains ES format, and `dist`, which I believe is for umd.

![explorer_2017-03-26_13-10-44](https://cloud.githubusercontent.com/assets/4460311/24330403/d04500ba-1225-11e7-90cd-2fc21c7271e1.png)

Now as I've seen this, I realized that for some reason JSPM tries to load library from `lib`, which is cjs, while it had to use `es` dir. Though, I'm not sure will it fix issue or not, I will try to do this a bit later.

But in theory, cjs version should work just fine too, right?

Mentioned file looks different in built cjs version, of course, but I don't see here anything criminal:

![sublime_text_2017-03-26_13-15-15](https://cloud.githubusercontent.com/assets/4460311/24330430/51f82484-1226-11e7-8044-7663f041c305.png)

@erikras, would you have time to look at this? After all, you do know about internals much more than any of us...

**Comment by ArmorDarks** [comment]
Just for the test, I tried to pass to JSPM content of `es` dir as `lib`, so that it load ES version, and passed `format: 'esm'` to `package.json`, but it didn't work:

![chrome_2017-03-26_13-25-03](https://cloud.githubusercontent.com/assets/4460311/24330488/d70ffb64-1227-11e7-8fe0-b6893438c9eb.png)

Here is content of `es/index.js` which passed as `lib/index.js`:

![sublime_text_2017-03-26_13-27-50](https://cloud.githubusercontent.com/assets/4460311/24330501/11603bee-1228-11e7-81f2-dd6f5575f122.png)

Apparently it's because I do not understand clearly how exactly it should work.

**Comment by ArmorDarks** [comment]
Okey, I figured it out. That was tricky!

You see, with JSPM beta.41 the source of trouble is this:

![chrome_2017-03-26_13-46-50](https://cloud.githubusercontent.com/assets/4460311/24330610/08ee5510-122b-11e7-804b-7dc4d76c36dd.png)

When redux-form tries to spread it into `...formActions`, this property leaks inside `formActions` variable too.

Then when variable passed to [this function](https://github.com/erikras/redux-form/blob/v6.6.0/src/reduxForm.js#L638) where lodash `mapValues` iterates upon each property and calls `bindForm` for each:

```js
const boundFormACs = mapValues(formActions, bindForm)
```

`bidForm` tries to bind each property (which originally contains only functions) with `.bind` method:

```js
const bindForm = actionCreator => actionCreator.bind(null, initialProps.form)
```

And now it should be pretty much obvious what happens...

Since `formActions` contains among other properties `esModule: true` _which isn't a function_, attempts to call `.bind` method on it results in error.

Dirty fix is to ignore `__esModule` property or anything that isn't a function:

```js
const bindForm = actionCreator => {
  if (actionCreator.__esModule) return
  return actionCreator.bind(null, initialProps.form)
}
```

Doesn't look good, though...

**Comment by ArmorDarks** [comment]
Title of this issue should be changed, because it's misleading and not about export (in both cases content properly imported as Object), but about injected `__esModule` property which introduces breaking change to 3rd-party libraries.

The question is how to treat it? I suppose when `__esModule` has been introduced, it was done under assumption that it won't break any 3rd-party code, but as we can see, it does.

**Comment by guybedford** [comment]
`__esModule` is supposed to be non-iterable, so shouldn't be picked up by the object iterator. So the fix for this is likely finding out what is setting `__esModule`, and ensuring it is setting it in the correct way.

The transpiler in use is likely the source of this property... what transpiler are you using in this project?

**Comment by ArmorDarks** [comment]
Redux-form uses babel for transpilation, as can be seen [here](https://github.com/erikras/redux-form/blob/master/package.json#L14)

In our personal project we're using JSPM 0.17.0-beta.41 with Babel as a transpiler and following JSPM config (I've removed `devConfig` to avoid clutter):

```js
SystemJS.config({
  baseURL: "source/scripts",
  browserConfig: {
    "paths": {
      "npm:": "/jspm_packages/npm/",
      "github:": "/jspm_packages/github/",
      "kotsu/": ""
    }
  },
  nodeConfig: {
    "paths": {
      "npm:": "jspm_packages/npm",
      "github:": "jspm_packages/github",
      "kotsu/": "source/scripts/"
    }
  },
  transpiler: "plugin-babel",
  packages: {
    "kotsu": {
      "main": "main.js",
      "format": "esm",
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "presets": [
              "babel-preset-react"
            ],
            "plugins": [
              "babel-plugin-transform-react-jsx-self",
              "babel-plugin-transform-react-jsx-source"
            ]
          }
        }
      }
    }
  },
  map: {
    "@hot": "@empty"
  }
});
```

Everything else auto-generated by JSPM and not touched.

In `package.json` we have following:

```js
  "jspm": {
    "name": "kotsu",
    "main": "main.js",
    "dependencies": {
      "babel-polyfill": "npm:babel-polyfill@^6.23.0",
      "lodash": "npm:lodash@^4.17.4",
      "moment": "npm:moment@^2.18.0",
      "numbro": "npm:numbro@^1.9.3",
      "react-router-redux": "npm:react-router-redux@^4.0.8",
      "react-router-scroll": "npm:react-router-scroll@^0.4.1",
      "redux-form": "npm:redux-form@^6.6.0",
      "redux-immutable-state-invariant": "npm:redux-immutable-state-invariant@^2.0.0",
      "redux-logger": "npm:redux-logger@^2.8.2",
      "redux-thunk": "npm:redux-thunk@^2.2.0"
    },
    "devDependencies": {
      "babel-plugin-transform-react-jsx-self": "npm:babel-plugin-transform-react-jsx-self@^6.22.0",
      "babel-plugin-transform-react-jsx-source": "npm:babel-plugin-transform-react-jsx-source@^6.22.0",
      "babel-preset-react": "npm:babel-preset-react@^6.23.0",
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.21",
      "systemjs-hot-reloader": "npm:systemjs-hot-reloader@^1.1.0"
    },
    "peerDependencies": {
      "assert": "npm:jspm-nodelibs-assert@^0.2.0",
      "buffer": "npm:jspm-nodelibs-buffer@^0.2.0",
      "child_process": "npm:jspm-nodelibs-child_process@^0.2.0",
      "constants": "npm:jspm-nodelibs-constants@^0.2.0",
      "crypto": "npm:jspm-nodelibs-crypto@^0.2.0",
      "domain": "npm:jspm-nodelibs-domain@^0.2.0",
      "events": "npm:jspm-nodelibs-events@^0.2.0",
      "fs": "npm:jspm-nodelibs-fs@^0.2.0",
      "history": "npm:history@^3.0.0",
      "http": "npm:jspm-nodelibs-http@^0.2.0",
      "https": "npm:jspm-nodelibs-https@^0.2.0",
      "os": "npm:jspm-nodelibs-os@^0.2.0",
      "path": "npm:jspm-nodelibs-path@^0.2.0",
      "process": "npm:jspm-nodelibs-process@^0.2.0",
      "react": "npm:react@^15.4.2",
      "react-dom": "npm:react-dom@^15.4.2",
      "react-redux": "npm:react-redux@^5.0.3",
      "react-router": "npm:react-router@3.0.2",
      "redux": "npm:redux@^3.6.0",
      "stream": "npm:jspm-nodelibs-stream@^0.2.0",
      "string_decoder": "npm:jspm-nodelibs-string_decoder@^0.2.0",
      "url": "npm:jspm-nodelibs-url@^0.2.0",
      "util": "npm:jspm-nodelibs-util@^0.2.0",
      "vm": "npm:jspm-nodelibs-vm@^0.2.0",
      "zlib": "npm:jspm-nodelibs-zlib@^0.2.0"
    },
    "overrides": {
      "npm:browserify-zlib@0.1.4": {
        "dependencies": {
          "readable-stream": "^2.0.2",
          "pako": "~0.2.0"
        },
        "map": {
          "_stream_transform": "readable-stream/transform"
        }
      },
      "npm:inherits@2.0.3": {
        "ignore": [
          "test.js"
        ]
      },
      "npm:lodash@4.17.4": {
        "map": {
          "buffer": "@empty",
          "process": "@empty"
        }
      },
      "npm:moment@2.18.0": {
        "jspmNodeConversion": false
      },
      "npm:numbro@1.9.3": {
        "format": "global"
      }
    }
  },
```

**Comment by ArmorDarks** [comment]
Just to ensure that it isn't `systemjs-hot-reloader` fault, I removed it and loaded main package directly with `System.import`.

Unfortunately, same result.

To be honest, I don't know how exactly to check is value iterable. I just tried to log `importedActions` content in `for (let e in importedActions) loop, I guess it should print only iterable values:

![chrome_2017-03-26_17-38-24](https://cloud.githubusercontent.com/assets/4460311/24332194/0e2e6bbc-124b-11e7-8b22-5acd8071cc2b.png)

As you can see, for some reason `__esModule` indeed became iterable, and thus passed down to `...formActions`, and takes part in loop of `mapValues` too.

Worth noting, that `importedActions` is a top-level occurrence of this property, so it definitely gets `__esModule` defined as iterable during import, but I do not understand why it happens.

**Comment by guybedford** [comment]
Ok it seems this is a consequence of the interop change in https://github.com/ModuleLoader/es-module-loader/releases/tag/2.1.0.

The issue is that we must still provide the original version of the module to existing CJS environments, even though it has been lifted into an ES module for the __esModule flag.

I'll aim to work on a fix for this Thursday.

**Comment by ArmorDarks** [comment]
Great, thanks!

Though, it's strange

I read this:

```js
Object.defineProperty(moduleObj, '__esModule', {
  value: true
});
```

As far as I know, defined property _should not be enumerable_ by default, unless you specify it as enumerable explicitly with `enumerable: true`. So it shouldn't introduce any issues.

Should I make small repository where particularly this issue with `redux-form` will be reproducible? Or it won't help?

**Comment by guybedford** [comment]
The specific issue is that all exports of actual ES module namespaces are enumerable by definition in the spec, and we're including the `__esModule` in that representation of the module.

**Comment by guybedford** [comment]
No need for a replication, I think I've got a handle on it.

**Comment by guybedford** [comment]
It's turned out that this is a good argument for reverting the approach taken in https://github.com/systemjs/systemjs/issues/1563#issuecomment-277175833, which was released in 0.20.6.

I've reverted this interop adjustment in https://github.com/ModuleLoader/es-module-loader/commit/d0f1eb2428f692595f10db6aa194b102297292e9 and https://github.com/systemjs/systemjs/commit/5c3484ffb2195a719e2878de3f859a6e733f51c9.

**Comment by guybedford** [comment]
Released in 0.20.11 (https://github.com/systemjs/systemjs/releases/tag/0.20.11), let me know if this works for you on this release.

**Comment by ArmorDarks** [comment]
It fixed issue, thanks a lot!

Any ETA for releasing it with JSPM?
