### ISSUE TITLE
defaultExtension: js as the default package config

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#759]
When we turn off the global `defaultJSExtensions`, all packages will need to explicitly have `.js` requires in them.

Most package on npm for example don't have this.

To ensure the ease-of-use remains, we can set `defaultExtension: 'js'` as the default **for all packages**, which can then be altered per-package.

This does create a difference in behaviour between packages and normal imports - `System.import('./x')` will request `/path/to/index/x`, while `System.import('some-package/x')` will request `some-package/x.js`, but this encourages users to explicitly include the extension when first experimenting with the loader, creating a good habit and then ensures that Node packages will likely work with SystemJS.

To go with 0.19.

**Comment by johnpapa** [comment]
How will this play out for loading TypeScript in dev time environments?

**Comment by guybedford** [comment]
For TypeScript packages, the `defaultExtension` can be set to `ts` or if the TypeScript has been transpiled and the extension changed it would work fine under a `js` extension too. Just let me know if that answers your question or not!

**Comment by typhonrt** [comment]
I'd like to understand the implications of removing defaultJSExtensions as in the last week I have converted my framework / web app to ES6 and all of the best practices (plugin extension at end of import, adding extension / .js, etc. to all my framework / web app imports).  I then went to check if I could remove "defaultJSExtensions: true" from config.js... All my code is fine, but now that I have a bunch of Babel dependencies for ES6 of course I had to add ".js" for everything in config.js including for the babel dependencies. The huge problem though is that Babel itself does bare require imports without extension internally / re: your statement about npm packages not including extension. For instance the next file I was led to was "babel-core@5.8.23.js" which is a basic require statement 'module.exports = require("npm:babel-core@5.8.23/browser");' Adding .js to "browser" gets things further along until Babel attempts to load more modules / plugins...  It does seem that it will be necessary to provide "defaultExtension: js" for Babel usage as I certainly don't want to go through the Babel code adding extensions. 

For now I'm going to just keep "defaultJSExtensions" enabled for use w/ Babel, but if there is an advised path forward that works with Babel I'd be glad to test it out before 0.19 hits...

**Comment by guybedford** [comment]
@typhonrt package configuration defaultExtensions handles these cases. And the default for that in 0.19 is also to provide .js by default.

**Comment by guybedford** [comment]
Released in 0.19.0.

**Comment by onlywei** [comment]
@guybedford  Slightly confused, I just set up JSPM 0.16.2 not so long ago and created my config file with `jspm init`. Inside that file, there is no "package" configuration. Right now I just have the:

 `defaultJSExtensions: true`

After upgrading, if I turn this OFF (or delete the line), then I experience the same thing that @typhonrt described above. I tried adding `defaultExtension: 'js'` to my config, but it did not seem to do anything.

**Comment by guybedford** [comment]
Read http://guybedford.com/jspm-0.16 if you're interested in this property and why we need it in jspm 0.16.

**Comment by todoubaba** [comment]
@guybedford When dev with typescript, this makes it impossible to use `import './x' `.

**Comment by guybedford** [comment]
@todouba you can set defaultExtension: 'ts' or false for the package, this
is just the default.

**Comment by onlywei** [comment]
All of the things I am reading seem to want me to stop using `defaultJSExtensions: true`, but yet still when I turn it off (even after upgrade), I cannot load Babel (as @typhonrt described). The documentation seems to suggest that I should use package configuration, but babel is something that comes pre-set-up using `jspm init`, and is not a member of any package. Am I supposed to change my System config manually to something like this?:

```
System.config({
  packages: {
    'jspm_packages': {
      defaultExtension: 'js',
      map: { "babel", "babel-runtime", ... }
    }
  }
}
```

**Comment by guybedford** [comment]
Yes exactly, jspm 0.17 needs some bigger changes to fully support
defaultJSExtensions false. Package-level disabling with defaultExtension is
the way to handle this in jspm 0.16 until then.

**Comment by johnpapa** [comment]
@guybedford 

Perhaps it is worth explaining how this works with TS in the docs.

For example, at dev time you want a module to use `*.ts` so we get the dev time tooling. But at run time you want it to use `*.js` as that is what runs in the browser.

Any recommendations on how to configure this should go in the docs, IMO. Thoughts?

**Comment by todoubaba** [comment]
@guybedford I use the transpiled file in browser, not load .ts file directly.

**Comment by todoubaba** [comment]
`defaultJSExtensions: true` still working in 0.19.0

**Comment by guybedford** [comment]
@johnpapa the TS workflow isn't as polished as I'd like it to be, the internal layer can't handle things like definition files which isn't ideal - I'd recommend most users to use https://github.com/frankwallis/plugin-typescript as it provides a much more comprehensive workflow, and will be the main project for TypeScript support in SystemJS and jspm going forward (the internal transpilation will be deprecated with https://github.com/systemjs/systemjs/issues/579).

In terms of getting users on board with these workflows, simply popularizing that plugin would be the task here.

As for the exact question - yes altering the configuration would be necessary to correspond to the transpilation process if wanting to switch from `ts` to `js` extensions.

**Comment by todoubaba** [comment]
@guybedford Just `defaultJSExtensions: true` in config works well in gulp-typescript workflow. Without it , the browser will load `/path/to/index/x` instead of  `/path/to/index/x.js`.

**Comment by guybedford** [comment]
@todoubaba yes that is by design. If you define `/path/to/index` as a package via package configuration:

```javascript
System.config({
  packages: {
    '/path/to/index': {
      // .. nothing is even necessary here ..
      main: 'x'
    }
  }
});
```

Then it will be seen as a package, and `js` extensions will be added automatically.

**Comment by todoubaba** [comment]
@guybedford `/path/to/x` is transpiled from typescript statement `import {X} from './x'`. Do you means I have config all these relative imports in `System.config`?

**Comment by guybedford** [comment]
@todoubaba a package is a folder not a module, so as long as your code is contained within the package path as its parent, you will get the behaviour. See the package docs at https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages.

**Comment by todoubaba** [comment]
@guybedford When there is no package configed, `defaultJSExtensions` affects the relative module loading. I'm just confused about the doc saids "Note that this is a compatibility property for transitioning to using explicit extensions and will be deprecated in future."

**Comment by guybedford** [comment]
@todoubaba if you can clarify what exactly about this is the confusion here, I'm happy to explain further.

**Comment by todoubaba** [comment]
@guybedford When `defaultJSExtensions` is deprecated or "turn off", how to "using explicit extensions" in `import {X} from './x'`? My config currently is
```
System.config({
    defaultJSExtensions: true
});
```

**Comment by guybedford** [comment]
By configuring the code for that folder as a package.

**Comment by todoubaba** [comment]
Thanks, I'll try.

**Comment by pcompassion** [comment]
We have many top level folders 

      "app1": {
          "defaultExtension": "js"
      },
      "app2": {
          "defaultExtension": "js"
      },

and so on, is there a way to do this for every apps?

**Comment by guybedford** [comment]
@pcompassion `defaultExtension: 'js'` is actually already the package default. Just `System.config({ packages: { 'app1': {}, 'app2': {} } })` is enough.

**Comment by pcompassion** [comment]
@guybedford Thanks for answer. 

Still I have to list all the `app1` `app2` and so on.   

with `"directories": {"baseURL": 'static'}` in package.json.

I have so many directories (packages) to include to config.
I'm using django and I guess many people using django has the similar static folder structure.  
(http://stackoverflow.com/a/22926208/433570)

![screen shot 2016-09-08 at 6 57 41 pm](https://cloud.githubusercontent.com/assets/84749/18345378/288d26ca-75f6-11e6-92e0-c33b9cd155e3.png)

**Comment by guybedford** [comment]
@pcompassion perhaps make the base-level folder a package then:

```javascript
packages: {
  '.': {}
}
```

**Comment by pcompassion** [comment]
oh shoot, I read somewhere it's not possible to use `./` or `../` in packages or paths. 

So it is possible. Thank you!

**Comment by pcompassion** [comment]
https://github.com/systemjs/systemjs/pull/1049/files?short_path=762c0f6&unchanged=expanded#packages

The following is about paths, but I think I can't have '.' in packages either. I tried it and it doesn't work.
> A token may not begin with path information, i.e. "./", "../" or "/", nor with server information, like protocol://server

**Comment by guybedford** [comment]
Package names accept any valid unnormalized module name.

**Comment by yeganehaym** [comment]
any improve of typescript files that are converted to js files?
after updating to new systemjs version, my project is not working any more

**Comment by owlcode** [comment]
@yeganehaym plugin-typescript ?
