### ISSUE TITLE
vue-class-component default not working in SystemJS 5.0

### ISSUE THREAD

**Issue by viT-1** [systemjs/systemjs#1989]
[Last commit](https://github.com/viT-1/systemjs-ts-es6-vue/commit/ffa78019139f8e760898c3669e7667d644654fa5) in my repo caused an error
TypeError: vue_class_component_1.default is not a function

importmap.json
```
{
	"imports": {
		"vue": "https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.min.js",
		"vue-class-component": "https://cdn.jsdelivr.net/npm/vue-class-component@7.1.0/dist/vue-class-component.min.js"
	}
} 
```

Way to reproduce:
1) npm run deploy
2) npm run www
3) browser loading http://localhost:3000/
