### ISSUE TITLE
"angular.module is not a function" on SystemJS v0.19.23

### ISSUE THREAD

**Issue by mfidemraizer** [systemjs/systemjs#1131]
Hey,

After upgrading to v0.19.30, now some Angular 1.x module fails to load because it finds that "angular.module" isn't a function. 

I've already checked that Angular is already loaded in the global scope when the sentence requiring it is executed (and it fails).

In my case, for now, it's `angular-simple-logger`, and the line looks as follows:

       var angular = require('angular');

       angular.module('nemLogging', []);

I can't figure out how to solve this issue.

Thank you in advance

**Comment by papasnippy** [comment]
Did you tried shim this module in meta with module type like commonjs?

**Comment by guybedford** [comment]
What is the value of `angular` in the above then? It would be worth logging that to see how it differs.

**Comment by mfidemraizer** [comment]
It's an empty object (i.e. `{}`).

I've found what's causing the problem. Because I'm having big troubles integrating Kendo UI, I solved this first problem adding both Angular and Kendo UI as regular `<script>` elements. When I do that, it's when I get `angular` as an empty object. 

I know it's a bad practice, but since the project I'm working in is in a very early stage of development, and I tried to temporarily solve the issue this way with no luck, because it ends up in the current issue with angular.

**Comment by tomsaleeba** [comment]
Not sure if this file was available when you had the problem but I've just fixed this same problem by using the `light` versions of the angular-simple-logger. For example, instead of using the `index.js` file, that has the lines you spoke of, use the `index.light.js` one (https://github.com/nmccready/angular-simple-logger/blob/master/dist/index.light.js) which omits those lines.
