### ISSUE TITLE
0.17 Promise.all no longer working

### ISSUE THREAD

**Issue by probins** [systemjs/systemjs#498]
```js
Promise.all(
  imports.map(System.import.bind(System))
);
```
worked in 0.16, but fails in 0.17 'n.indexOf is not a function' - seems to be parentName in plugin addon that's failing.

Without the bind (which used to work in a previous version), fails 'n.normalize is not a function'

**Comment by guybedford** [comment]
This works fine for me, I think the error is most likely unrelated.

**Comment by probins** [comment]
How did you test this? I just tried a really simple example. I created 2 'modules' which just do a console.log, and then loaded an empty html. `System.import('m1.js')` and `System.import('m1.js')` work, but `Promise.all(['m1.js','m2.js'].map(System.import.bind(System)))` fails.

**Comment by probins** [comment]
using dist/system.js

**Comment by guybedford** [comment]
@probins which environment are you testing in here?

**Comment by guybedford** [comment]
It appears the map function returns an index as the second argument, which is interpreted as the parentName for the System.import function!

**Comment by probins** [comment]
ah yes, that will be it :-) I was testing in Chrome

**Comment by probins** [comment]
there's the same problem with forEach, but shuffling the code around a bit resolves the issue:
```js
var promises = [];
['m1.js','m2.js'].forEach(function(m){
  promises.push(System.import(m));
});
Promise.all(promises).then(function(modules){...});
```
which has the extra advantage of removing the bind().

Might be useful to document this somewhere. Any idea where? Readme basic use, perhaps?
