### ISSUE TITLE
esModule property not honored in package meta definition

### ISSUE THREAD

**Issue by mikol-styra** [systemjs/systemjs#1764]
After upgrading from 0.19.41 to 0.20.19 (actually upgrading JSPM from 0.17.0-beta.32 to 0.17.0-beta.47), using `import {...} from '...'` syntax with a CJS module no longer works. With 0.19.41, I didn’t need any special configuration options. With 0.20.19, the `esModule` property doesn’t seem to work as advertised.

I have the following configuration (in part):

```
System.config({
...
  packages: {
    "src": {
      "format": "esm",
      "main": "client.js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "plugins": [
              "babel-plugin-transform-object-assign",
              "babel-plugin-transform-react-jsx"
            ]
          }
        }
      }
    },
...
    "src/lang": {
      "meta": {
        "*.js": {
          "format": "cjs",
          "loader": "plugin-babel",
          "babelOptions": {
            "modularRuntime": false
          }
        },
        "parser.js": {
          "esModule": true
        }
      }
    }
  },
...
})
```

I can tell that the package configuration is otherwise working – for example, I will see `TypeError: require is not a function` if I use `"parser.js": {"format": "esm"}`.

`parser.js` is generated by [PEG.js](https://github.com/pegjs/pegjs) and includes the following exports:

```
module.exports = {
  SyntaxError: peg$SyntaxError,
  parse:       peg$parse
};
```

When I `import {parse} from 'src/lang/parser`, `parse` is `undefined`.

When I `import _, {parse} from 'src/lang/parser'`, `_` is:

```
{
  SyntaxError: function peg$SyntaxError(message, expected, found, location) {...},
  parse: function peg$parse(input, options) {...}
}
```

**Comment by mikol-styra** [comment]
Also: Adding `module.exports.__esModule = true` to `parser.js` works as expected.

**Comment by dak** [comment]
@mikol-styra I ran into a very similar problem when upgrading to 0.20 as well (see: https://github.com/jspm/jspm-cli/issues/2283).

**Comment by mikol-styra** [comment]
Thanks for the tip, @dak. Unfortunately, I still can’t get it to work in my environment. Maybe it’s that you are using absolute `http://` URLs (which are not really an option for me)? @guybedford – Is the `"configured"` property significant? Where is that documented?

**Comment by mikol-styra** [comment]
And the issue applies to _any_ attempt to `import {...} from '...'` if the imported module/member is CommonJS. That means that it is also affecting a raft of third-party modules, which would be infeasible for me to patch.

**Comment by dak** [comment]
@mikol-styra I ultimately didn't use the absolute URLs, either. Below is the current working config I've been using:

```json
"overrides": {
    "npm:incremental-dom@0.5.1": {
        "defaultExtension": "js",
        "main": "dist/incremental-dom.js",
        "format": "amd",
        "meta": {
            "dist/incremental-dom.js": {
                "esModule": true
            }
        },
        "configured": true
    }
}
```

The other solution I've found is switching to compiling everything as system modules, rather than CommonJS or AMD, which is something else I've started doing recently (I had been putting it off due to the complexity of getting it to work with Ava, but that's a different issue).

I believe the `configured` property was significant, although I'm unable to test it atm to confirm. I'll try to do some testing tonight and I'll update with my results. I also was unable to find any documentation on it.

**Comment by mikol-styra** [comment]
Thanks, @dak. Unfortunately, still no luck…

**Comment by youk** [comment]
`esModule: true` works for me when importing from lodash as `import {map} from 'lodash'`. SystemJS 0.20.19 with the following configuration:
```
SystemJS.config({
    baseURL: 'node_modules',
    packageConfigPaths: ['*/package.json'],
    meta: {
        'lodash/lodash.js': {
            esModule: true
        }
    }
})
```

**Comment by mikol-styra** [comment]
Maybe I should move this over to JSPM… My packages are complicated by JSPM dependency management. I have 6 lodash packages, for example.

```
lodash-es@4.17.4
lodash.flattendeep@4.4.0
lodash.isequal@4.5.0
lodash@4.16.3
lodash@4.16.4
lodash@4.17.4
```

Still, this had been working with 0.19.41…

It’d be great to find a solution that didn’t involve manually futzing with each and every package configuration.

**Comment by youk** [comment]
Do you generate SystemJS config using JSPM? It's just SystemJS in the end, so it's either working config or not. It should not be that hard create a minimal config to track down the problem part.

**Comment by mikol-styra** [comment]
Wildcard doesn’t work. For whatever reason, my JSPM config file is split into 2 `System.config({...})` calls. Using wildcard in the first call doesn’t change anything. Using it in the second call breaks `jspm run ./src/server.js`:

```
file:///.../src/server.js: Cannot read property 'keyword' of undefined
 Instantiating /.../src/server.js
 Loading ./src/server.js
 TypeError: file:///.../src/server.js: Cannot read property 'keyword' of undefined
   at convertJSXIdentifier (file:///.../jspm_packages/npm/babel-helper-builder-react-jsx@6.9.0/lib/index.js:32:61)
   at buildElementCall (file:///.../jspm_packages/npm/babel-helper-builder-react-jsx@6.9.0/lib/index.js:71:19)
   at PluginPass.exit (file:///.../jspm_packages/npm/babel-helper-builder-react-jsx@6.9.0/lib/index.js:14:22)
   at newFn (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:32693:23)
   at NodePath._call (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:30689:20)
   at NodePath.call (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:30661:19)
   at NodePath.visit (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:30730:10)
   at TraversalContext.visitQueue (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:32192:18)
   at TraversalContext.visitSingle (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:32150:21)
   at TraversalContext.visit (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:32234:21)
   at Function.traverse.node (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:33822:19)
   at NodePath.visit (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:30728:21)
   at TraversalContext.visitQueue (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:32192:18)
   at TraversalContext.visitMultiple (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:32145:19)
   at TraversalContext.visit (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:32232:21)
   at Function.traverse.node (file:///.../jspm_packages/npm/systemjs-plugin-babel@0.0.16/systemjs-babel-node.js:33822:19)
```

Per the 0.20.0 release notes, I ended up replacing all of my offending imports with Node/CJS-safe ones:

```
import Parser from 'src/lang/parser'
const parse = Parser.parse
```

Which was easier than pairing down to a minimal config to reproduce the problem.
